# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        npm ci
        npm run build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.APP_VERSION }}
        release_name: Release ${{ env.APP_VERSION }}
        body: |
          Release ${{ env.APP_VERSION }}
        draft: false
        prerelease: false
    - name: Upload exe
      id: upload_exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/MylNext Setup ${{env.APP_VERSION}}.exe
        asset_name: MylNext Setup ${{env.APP_VERSION}}.exe
        asset_content_type: application/octet-stream
    - name: Upload dmg
      id: upload_dmg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/MylNext-${{ env.APP_VERSION }}.dmg
        asset_name: MylNext-${{ env.APP_VERSION }}.dmg
        asset_content_type: application/octet-stream

